/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tarea11prog;

import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static tarea11prog.Metodos.conectado;





/**
 *
 * @author FRANCISCO
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        
        //creo los botones principales si se clica uno otro se desclica
        initComponents();
      buttonGroup1.add(this.radioMenuClientes);   
      buttonGroup1.add(this.radioMenuClientes2);
      
      buttonGroup1.add(this.menuCrearEscrituras);   
      buttonGroup1.add(this.radioMenuEscrituras2);
      
      buttonGroup1.add(this.radioMenuEscriturasClientes);     
      buttonGroup1.add(this.radioMenuEscriturasClientes2);
      
      buttonGroup1.add(this.radioBuscar);
 
      // de inicio se muerta el botton rojo
      metodos.mostrarImagen(labelestado,"pilotorojo.jpg");
      
   
     
      
    }
     // declaro los Jpanel que voy a usar
    private VistaCliente                    vtc;
    private VistaEscrituraCliente           vec;
    private VistaEscritura                  vte;
    private Buscar                          bus;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem5 = new javax.swing.JRadioButtonMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        btnSalirAplicacion = new javax.swing.JButton();
        btnConectarbaseDatos = new javax.swing.JButton();
        estadolb = new javax.swing.JLabel();
        labelestado = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuCrearTablas = new javax.swing.JMenu();
        radioMenuClientes = new javax.swing.JRadioButtonMenuItem();
        menuCrearEscrituras = new javax.swing.JRadioButtonMenuItem();
        radioMenuEscriturasClientes = new javax.swing.JRadioButtonMenuItem();
        menuVisualizardatos = new javax.swing.JMenu();
        radioMenuClientes2 = new javax.swing.JRadioButtonMenuItem();
        radioMenuEscrituras2 = new javax.swing.JRadioButtonMenuItem();
        radioMenuEscriturasClientes2 = new javax.swing.JRadioButtonMenuItem();
        menuBuscar = new javax.swing.JMenu();
        radioBuscar = new javax.swing.JRadioButtonMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem8.setText("jMenuItem8");

        jRadioButtonMenuItem5.setSelected(true);
        jRadioButtonMenuItem5.setText("jRadioButtonMenuItem5");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));
        setPreferredSize(new java.awt.Dimension(850, 800));

        btnSalirAplicacion.setText("Salir Aplicacion");
        btnSalirAplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAplicacionActionPerformed(evt);
            }
        });

        btnConectarbaseDatos.setText("Conectar");
        btnConectarbaseDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarbaseDatosActionPerformed(evt);
            }
        });

        estadolb.setText("estado");

        labelestado.setText("imagen");

        PanelPrincipal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(500, 550));

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );

        MenuCrearTablas.setText("Crear tablas");
        MenuCrearTablas.setEnabled(false);
        MenuCrearTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCrearTablasActionPerformed(evt);
            }
        });

        radioMenuClientes.setText("Clientes");
        radioMenuClientes.setEnabled(false);
        radioMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMenuClientesActionPerformed(evt);
            }
        });
        MenuCrearTablas.add(radioMenuClientes);

        menuCrearEscrituras.setText("Escritura");
        menuCrearEscrituras.setEnabled(false);
        menuCrearEscrituras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearEscriturasActionPerformed(evt);
            }
        });
        MenuCrearTablas.add(menuCrearEscrituras);

        radioMenuEscriturasClientes.setText("EscriturasClientes");
        radioMenuEscriturasClientes.setEnabled(false);
        radioMenuEscriturasClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMenuEscriturasClientesActionPerformed(evt);
            }
        });
        MenuCrearTablas.add(radioMenuEscriturasClientes);

        jMenuBar1.add(MenuCrearTablas);

        menuVisualizardatos.setText("Visualizar Datos");
        menuVisualizardatos.setEnabled(false);
        menuVisualizardatos.setFocusable(false);

        radioMenuClientes2.setText("Clientes");
        radioMenuClientes2.setEnabled(false);
        radioMenuClientes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMenuClientes2ActionPerformed(evt);
            }
        });
        menuVisualizardatos.add(radioMenuClientes2);

        radioMenuEscrituras2.setText("Escrituras");
        radioMenuEscrituras2.setEnabled(false);
        radioMenuEscrituras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMenuEscrituras2ActionPerformed(evt);
            }
        });
        menuVisualizardatos.add(radioMenuEscrituras2);

        radioMenuEscriturasClientes2.setText("EscriturasClientes");
        radioMenuEscriturasClientes2.setEnabled(false);
        radioMenuEscriturasClientes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMenuEscriturasClientes2ActionPerformed(evt);
            }
        });
        menuVisualizardatos.add(radioMenuEscriturasClientes2);

        jMenuBar1.add(menuVisualizardatos);

        menuBuscar.setText("Buscar");
        menuBuscar.setEnabled(false);

        radioBuscar.setSelected(true);
        radioBuscar.setText("Buscar");
        radioBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBuscarActionPerformed(evt);
            }
        });
        menuBuscar.add(radioBuscar);

        jMenuBar1.add(menuBuscar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(estadolb)
                        .addGap(18, 18, 18)
                        .addComponent(labelestado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConectarbaseDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnSalirAplicacion)))
                .addContainerGap(301, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(labelestado))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(estadolb)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConectarbaseDatos)
                    .addComponent(btnSalirAplicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMenuClientesActionPerformed
       
        // creo la tabla
        metodos.creartabla("Clientes");    
       //habilito el metor registros y deshabilito el crear tabla 
        radioMenuClientes2.setEnabled(true);       
        radioMenuClientes.setEnabled(false);
       //hablilito la opcion visualizar datos
        menuVisualizardatos.setEnabled(true);
    }//GEN-LAST:event_radioMenuClientesActionPerformed

    private void btnSalirAplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAplicacionActionPerformed
     
        System.exit(0);
        
    }//GEN-LAST:event_btnSalirAplicacionActionPerformed

    private void MenuCrearTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCrearTablasActionPerformed
        
        
               
    }//GEN-LAST:event_MenuCrearTablasActionPerformed

    private void menuCrearEscriturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearEscriturasActionPerformed
       // habilito escritura
        metodos.creartabla("Escrituras");
        
       // habilito meter registros y deshabilito crear tabla
        radioMenuEscrituras2.setEnabled(true);
        menuCrearEscrituras.setEnabled(false);
        
        // habilito ver tablas de Escrituras
        menuVisualizardatos.setEnabled(true);
    }//GEN-LAST:event_menuCrearEscriturasActionPerformed

    private void btnConectarbaseDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarbaseDatosActionPerformed
        
        // conecto con la base de datos
        metodos.conectarBD("notaria", "root", "system");
        if(conectado){
            try {
                metodos.mostrarImagen(labelestado,"pilotoverde.jpg");
               // si esta creado habilito la opcion de  
                MenuCrearTablas.setEnabled(true);
                if(metodos.existetabla("Clientes")){
                    
                    radioMenuClientes2.setEnabled(true);
                    menuBuscar.setEnabled(true);
                }else{
                    
                    radioMenuClientes.setEnabled(true);
                }
                if(metodos.existetabla("Escrituras")){
               
                    radioMenuEscrituras2.setEnabled(true);
                    menuBuscar.setEnabled(true);
                    
                }else{
                    menuCrearEscrituras.setEnabled(true);
                }
                if(metodos.existetabla("EscriturasCliente")){
                  
                    radioMenuEscriturasClientes2.setEnabled(true);
                    menuBuscar.setEnabled(true);
              
                    
                }else{
                    
                     radioMenuEscriturasClientes.setEnabled(true);
                }
                
                
                menuVisualizardatos.setEnabled(true);
                
                
            } catch (SQLException ex) {
                Logger.getLogger(interfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        btnConectarbaseDatos.setEnabled(false);   
        }
        
        
        
    }//GEN-LAST:event_btnConectarbaseDatosActionPerformed

    private void radioMenuEscriturasClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMenuEscriturasClientesActionPerformed
        try {
            // como la tabla Escritura Clientes esta vinculada a las otras dos si no estan creadas 
            // no dejo crearla
            if(metodos.existetabla("Clientes")&& metodos.existetabla("Escrituras")){
                metodos.creartabla("EscriturasCliente");
              // una vez creada habilito la entrada de registros y deshabilito crear tablas
                radioMenuEscriturasClientes2.setEnabled(true);
                radioMenuEscriturasClientes.setEnabled(false);
                     
            }else{
                JOptionPane.showMessageDialog(this,"NO se han creado la tabla Clientes o Escrituras","Error",JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_radioMenuEscriturasClientesActionPerformed

    private void radioMenuClientes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMenuClientes2ActionPerformed
        
        //cuando seleccion el menu desplegable una opcion aparece una panel de la opcion elegida
        
        vtc = new VistaCliente();
        vtc.setSize(800,800);
        vtc.setLocation(5, 5);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(vtc,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        
        
        
        
        
    }//GEN-LAST:event_radioMenuClientes2ActionPerformed

    private void radioMenuEscrituras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMenuEscrituras2ActionPerformed
        
        //cuando seleccion el menu desplegable una opcion aparece una panel de la opcion elegida
        
        vte = new VistaEscritura();
        vte.setSize(800,800);
        vte.setLocation(5, 5);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(vte,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        
    }//GEN-LAST:event_radioMenuEscrituras2ActionPerformed

    private void radioMenuEscriturasClientes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMenuEscriturasClientes2ActionPerformed
        
        //cuando seleccion el menu desplegable una opcion aparece una panel de la opcion elegida
        
        vec = new VistaEscrituraCliente();
        vec.setSize(800,800);
        vec.setLocation(5, 5);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(vec,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        
    }//GEN-LAST:event_radioMenuEscriturasClientes2ActionPerformed

    private void radioBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBuscarActionPerformed
        
        bus = new Buscar();
        bus.setSize(800,800);
        bus.setLocation(5, 5);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(bus,BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
        
        
        
        
        
    }//GEN-LAST:event_radioBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            
              
                
            }
        });
        
   
    
        
        
        
   
    }
      
      // instancion la clase metodos para usar sus metodos
      Metodos metodos=new Metodos();
   
     
      
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCrearTablas;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton btnConectarbaseDatos;
    private javax.swing.JButton btnSalirAplicacion;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel estadolb;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem5;
    private javax.swing.JLabel labelestado;
    private javax.swing.JMenu menuBuscar;
    private javax.swing.JRadioButtonMenuItem menuCrearEscrituras;
    private javax.swing.JMenu menuVisualizardatos;
    private javax.swing.JRadioButtonMenuItem radioBuscar;
    private javax.swing.JRadioButtonMenuItem radioMenuClientes;
    private javax.swing.JRadioButtonMenuItem radioMenuClientes2;
    private javax.swing.JRadioButtonMenuItem radioMenuEscrituras2;
    private javax.swing.JRadioButtonMenuItem radioMenuEscriturasClientes;
    private javax.swing.JRadioButtonMenuItem radioMenuEscriturasClientes2;
    // End of variables declaration//GEN-END:variables
}
